name: nedo                                                                                                                                               
channels:
  - nvidia                                                                                                                                                 
  - conda-forge                                                                                                                                               
  - defaults                                                                                                                                                  
dependencies:
  - cuda-toolkit=11.8
  - cudnn
  - scipy
  - opencv
  - lap
  - filterpy
  - celery
  - celery[redis]
  - pandas
  - watchdog
  - pip:
    - qdrant-client
    - onnxruntime-gpu
